//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PioneerStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesQuantity
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public int StoreID { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Store Store { get; set; }
    }
}
