//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PioneerStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreDBEntities2 : DbContext
    {
        public StoreDBEntities2()
            : base("name=StoreDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<CategoriesQuantity> CategoriesQuantities { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Purchases_Bills> Purchases_Bills { get; set; }
        public virtual DbSet<Purchases_Bills_Details> Purchases_Bills_Details { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Sales_Bills> Sales_Bills { get; set; }
        public virtual DbSet<Sales_Bills_Details> Sales_Bills_Details { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
