//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PioneerStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Bills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales_Bills()
        {
            this.Sales_Bills_Details = new HashSet<Sales_Bills_Details>();
        }
    
        public int ID { get; set; }
        public int BillNumber { get; set; }
        public System.DateTime BillDate { get; set; }
        public int ClientID { get; set; }
        public decimal Total { get; set; }
        public decimal Payed { get; set; }
        public decimal Remain { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Bills_Details> Sales_Bills_Details { get; set; }
    }
}
